name: sphinx-docs

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install and set up Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV

    - name: Install docs dependencies
      run: |
        poetry install --with docs -vvv

    - name: Generate docs with Sphinx
      run: |
        cd docs
        poetry run sphinx-apidoc -f -o source ../pytrello2
        poetry run make html
        cd ..

    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
